version: "2"
services:
  mongo:
    container_name: mongo
    build: ./mongo/.
    restart: on-failure
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - network
  check:
    container_name: check
    restart: always
    build: ./check_status_api/.
    ports:
      - "8100:3000"
    networks:
      - network
  mock1:
    container_name: mock1
    restart: always
    build: ./deviceMock/.
    environment:
      - mock_name=mock1
      - mock_port=8001
      - local_ip=10.0.0.17
    ports:
      - "8001:3000"
    networks:
      - network
  mock2:
    container_name: mock2
    restart: always
    build: ./deviceMock/.
    environment:
      - mock_name=mock2
      - mock_port=8002
      - local_ip=10.0.0.17
    ports:
      - "8002:3000"
    networks:
      - network
  app:
    container_name: cortijo
    restart: always
    build: ./api/.
    ports:
      - "8000:3000"
    links:
      - mongo
    networks:
      - network
  front:
    container_name: front
    restart: always
    build: ./frontAng/.
    ports:
      - "80:80"
    networks:
      - network
networks:
  network:
