version: "3"
services:
  mongo:
    container_name: mongo
    build: ./mongo/.
    restart: "no"
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - network
  catordog:
    container_name: catordog
    restart: always
    build: ./cat_or_dog/.
    ports:
      - "8200:3000"
    networks:
      - network
  mock:
    container_name: mock
    restart: always
    build: ./deviceMock/.
    environment:
      - mock_name=mock
      - mock_port=8101
      - local_ip=192.168.1.50
    ports:
      - "8101:3000"
    networks:
      - network
  cortijo:
    container_name: cortijo
    restart: always
    build: ./cortijo/.
    ports:
      - "8000:3000"
    links:
      - mongo
    networks:
      - network
  auth:
    container_name: auth
    restart: always
    build: ./auth/.
    environment:
      - token_password=cortijo1
    ports:
      - "8010:3000"
    links:
      - mongo
    networks:
      - network
  front:
    container_name: front
    restart: always
    build: ./frontAng/.
    ports:
      - "443:80"
    networks:
      - network
networks:
  network:
