version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - network
  check:
    container_name: check
    restart: always
    build: ./check_status_api/.
    ports:
      - "8100:3000"
    networks:
      - network
  mock:
    container_name: mock
    restart: always
    build: ./deviceMock/.
    d:
      NAME=mock1
      PORT=8001
      IP=192.168.0.50
    ports:
      - "8001:3000"
    networks:
      - network
  app:
    container_name: cortijo
    restart: always
    build: .
    ports:
      - "8000:3000"
    links:
      - mongo
    networks:
      - network
networks:
  network:
