version: "2"
services:
  app:
    container_name: cortijo
    restart: always
    build: .
    ports:
      - "8000:3000"
    links:
      - mongo
    networks:
      - net
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - net
networks:
  net:
    driver: cortijo-network
