---
  log: "debug"
  timeout_check:  2000
  timeout_sensor: 2000
  times_before_block: 5
  refresh_delay: 0
  get_device_status_timeout: 5000
  switch_status_timeout: 5000
  get_data_timeout: 5000
  sensor_history: 1344
  version: "1.0.1"
