---
  log: "debug"
  timeout_check:  500000
  timeout_sensor: 1000
  refresh_delay: 2000
  get_device_status_timeout: 10000
  switch_status_timeout: 10000
  get_data_timeout: 10000
  version: "1.0.1"
