---
  db_url: mongodb://192.168.1.50:27017/cortijo
  socket_url: http://192.168.1.50:8200
  auth_url: http://192.168.1.50:8010
  publickey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7/RKCFiXE0XmGR9mT6YOztOqOVRJMZw3IcicQdfNZrdGmCm86WkfY54/UPeTHwzDJEdDsq3t1U7rBT6qAd5h+eSWqUvWM5mM28DNjmyG0gdYMec1f4yC4YDy/jNy7+diiKvhBmDRoGc83EXaepkLZ+na8hJNKMlf2cDEGhlR4BMRkoZTtgdf8x4kCXaZaI2ctI+UoFUr0Ai+AyUHnveD2X45rELr7sB1aW1IPDOT7Rq4qebzkkK3TDWWAoKvAjgfRSD7Zn/y/4iFzBXvq+vE/jn6JkjnKYumMYlxjdDkXw3ZU//RHGJnVoYcTgBp1p6sFJk3QWVGO2K+Tp84SPAdf enriqueramosmunoz@EnriquesMBP503
  privatekey: -----BEGIN OPENSSH PRIVATE KEY-----\
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn\
    NhAAAAAwEAAQAAAQEAu/0SghYlxNF5hkfZk+mDs7TqjlUSTGcNyHInEHXzWa3RpgpvOlpH\
    2OeP1D3kx8MwyRHQ7Kt7dVO6wU+qgHeYfnklqlL1jOZjNvAzY5shtIHWDHnNX+MguGA8v4\
    zcu/nYoir4QZg0aBnPNxF2nqZC2fp2vISTSjJX9nAxBoZUeATEZKGU7YHX/MeJAl2mWiNn\
    LSPlKBVK9AIvgMlB573g9l+OaxC6+7AdWltSDwzk+0auKnm85JCt0w1lgKCrwI4H0Ug+2Z\
    /8v+IhcwV76vrxP45+iZI5ymLpjGJcY3Q5F8N2VP/0RxiZ1aGHE4AadaerBSZN0FlRjtiv\
    k6fOEjwHXwAAA9iE8z0ThPM9EwAAAAdzc2gtcnNhAAABAQC7/RKCFiXE0XmGR9mT6YOztO\
    qOVRJMZw3IcicQdfNZrdGmCm86WkfY54/UPeTHwzDJEdDsq3t1U7rBT6qAd5h+eSWqUvWM\
    5mM28DNjmyG0gdYMec1f4yC4YDy/jNy7+diiKvhBmDRoGc83EXaepkLZ+na8hJNKMlf2cD\
    EGhlR4BMRkoZTtgdf8x4kCXaZaI2ctI+UoFUr0Ai+AyUHnveD2X45rELr7sB1aW1IPDOT7\
    Rq4qebzkkK3TDWWAoKvAjgfRSD7Zn/y/4iFzBXvq+vE/jn6JkjnKYumMYlxjdDkXw3ZU//\
    RHGJnVoYcTgBp1p6sFJk3QWVGO2K+Tp84SPAdfAAAAAwEAAQAAAQAnk2ajFlCLN+JSn6ux\
    lPaSDaNXpZc9mHBxY37P21UI6yv4vbee3ETF6DICZ6lTWMdbfTGzsYJDOAZYDhKCCyuCbL\
    S+P8rMB/CZL0ZSUOVun+rVI4tWBXXs+u2vEdOiiz3NHii3fniB9fUGzdlgGvZ192Gp3Gs5\
    spGMIyBfFEaSIWogZvW08haHaJGrK0f7pKWBSMiBXghkdjeQuS/cYNl7rcTU7oLiRte+eL\
    MCUpe9/9jKYE+IvAYjW1terR4V0ObwwUZQ4c6G7hTjyECswD8XQjknlJswtXLv6aSemrI4\
    ZPtyRFDuO559QHMjbxWQGolOp/xjYGDHgLKh49UbuRJJAAAAgBVU+FZf669nA6hzZNa4By\
    yPZ6C9TZcj/e3OqFNmYY9OCF52WdqJEY0vKp8klr/Ha0h4eJXkFR0tTt0vu4AUKJtBBRFh\
    u+j7wVTcbYCWXoewrjtSMEDrLPYQrG1jT1MhLeXea2DddAWGdiQEo6So/9JhTyuylabgkQ\
    I00m8vmYBLAAAAgQDtwCmJVsQX63Jsj0GtCj8HTTcDh3e4oJsJAz+kQyBanTZ4VwLRqroh\
    FT7Y+ymO044mihijJue92dnrJl3XNMkL/V5dm1UFPhr8zOd1JQtb+TqNT76bF9BFZgAPcD\
    alWuV6KtdfbwmWWaZvc3PxAx5wPIPfOb1RddAXqoIC3FWaowAAAIEAymsT1Dki4imB62CO\
    MbOOe1ZH4LcmSZm7kvGtJ+cQtx5y1PmpwZgt2nnV6znlQ9lj58qp6Tzl6SNiqvJmqfbLJf\
    2VZhLtl3jvPktKAuUqPNVXlwQrtB9Y9gZ/A3M+c9Jny04tfqkt21WOGCpZvUnJt+UXkT3s\
    Bi+bGWl7dg1tyBUAAAAgZW5yaXF1ZXJhbW9zbXVub3pARW5yaXF1ZXNNQlA1MDMBAgM=\
    -----END OPENSSH PRIVATE KEY-----
