apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cortijo
  namespace: cortijo
spec:
  dnsNames:
    - www.cortijodemazas.com
  secretName: cortijo-tls
  issuerRef:
    name: cortijo-letsncypt
  # acme:
  #   config:
  #   - http01:
  #     ingress: front
  #     domains:
  #     - www.cortijodemazas.com
