apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cortijo-letsncypt
  namespace: cortijo
spec:
  acme:
    server: https://www.cortijodemazas.com
    email: enriqueramosmunoz@gmail.com
    privateKeySecretRef:
      name: cortijo-letsncypt
    http01: {}
