---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cortijo-letsncypt
  namespace: cortijo
spec:
  acme:
    server: https://www.cortijodemazas.com
    email: enriqueramosmunoz@gmail.com
    privateKeySecretRef:
      name: cortijo-letsncypt
    http01: {}
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: selfsigned-cert
#   namespace: cert-manager-test
# spec:
#   dnsNames:
#     - example.com
#   secretName: selfsigned-cert-tls
#   issuerRef:
#     name: test-selfsigned
