version: "3.3"
services:
  cortijo_websocket:
    container_name: cortijo_websocket
    restart: on-failure
    build: .
    ports:
    - "3000:3000"
    - "3001:3001"
    volumes:
    - /home/ubuntu/cortijo/deployment/config_url.yaml:/root/scr/config_url.yaml:ro
